GET http://127.0.0.1:8000/start


####

POST http://127.0.0.1:8000/create
Content-Type: application/json

{
  "username": "Miguel",  
  "email": "email@example.com",
  "phone": "1234567890",
  "cpf_cnpj": "12345678901234",
  "password": "n"
}

###
POST http://127.0.0.1:8000/login
Content-Type: application/json

{
  "username": "admin",  
  "password": ""
}

###
POST http://127.0.0.1:8000/add
Content-Type: application/json

{
  "token": "token",
  "nPaginas": "1"
}